In [1]:
import altair as alt
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('churn.csv')
data0 = data

data.head()
data.count()

age                             36992
gender                          36992
security_no                     36992
region_category                 31564
membership_category             36992
joining_date                    36992
joined_through_referral         36992
referral_id                     36992
preferred_offer_types           36704
medium_of_operation             36992
internet_option                 36992
last_visit_time                 36992
days_since_last_login           36992
avg_time_spent                  36992
avg_transaction_value           36992
avg_frequency_login_days        36992
points_in_wallet                33549
used_special_discount           36992
offer_application_preference    36992
past_complaint                  36992
complaint_status                36992
feedback                        36992
churn_risk_score                36992
dtype: int64

In [2]:
data.dropna(inplace=True)
data.count()

age                             28373
gender                          28373
security_no                     28373
region_category                 28373
membership_category             28373
joining_date                    28373
joined_through_referral         28373
referral_id                     28373
preferred_offer_types           28373
medium_of_operation             28373
internet_option                 28373
last_visit_time                 28373
days_since_last_login           28373
avg_time_spent                  28373
avg_transaction_value           28373
avg_frequency_login_days        28373
points_in_wallet                28373
used_special_discount           28373
offer_application_preference    28373
past_complaint                  28373
complaint_status                28373
feedback                        28373
churn_risk_score                28373
dtype: int64

In [3]:
#remove negative values
data = data[data['days_since_last_login'] >= 0]
data['days_since_last_login'].sort_values(ascending=True)

11884     1
7102      1
6184      1
11751     1
26421     1
         ..
28048    26
27217    26
5791     26
21220    26
15593    26
Name: days_since_last_login, Length: 26821, dtype: int64

In [4]:
#remove rows with security_no length greater than 7
data = data[data['security_no'].str.len() < 8]
data['security_no'].str.len().sort_values(ascending=True)

0        7
24741    7
24739    7
24736    7
24735    7
        ..
12393    7
12391    7
12390    7
12359    7
36991    7
Name: security_no, Length: 26818, dtype: int64

In [5]:
#remove rows with avg_time_spent less than 0
data=data[data['avg_time_spent'] >= 0]
data.count()

age                             25537
gender                          25537
security_no                     25537
region_category                 25537
membership_category             25537
joining_date                    25537
joined_through_referral         25537
referral_id                     25537
preferred_offer_types           25537
medium_of_operation             25537
internet_option                 25537
last_visit_time                 25537
days_since_last_login           25537
avg_time_spent                  25537
avg_transaction_value           25537
avg_frequency_login_days        25537
points_in_wallet                25537
used_special_discount           25537
offer_application_preference    25537
past_complaint                  25537
complaint_status                25537
feedback                        25537
churn_risk_score                25537
dtype: int64

In [6]:
#remove rows with avg_transaction_value less than 0
data = data[data['avg_frequency_login_days'] != 'Error']
data.count()

age                             23132
gender                          23132
security_no                     23132
region_category                 23132
membership_category             23132
joining_date                    23132
joined_through_referral         23132
referral_id                     23132
preferred_offer_types           23132
medium_of_operation             23132
internet_option                 23132
last_visit_time                 23132
days_since_last_login           23132
avg_time_spent                  23132
avg_transaction_value           23132
avg_frequency_login_days        23132
points_in_wallet                23132
used_special_discount           23132
offer_application_preference    23132
past_complaint                  23132
complaint_status                23132
feedback                        23132
churn_risk_score                23132
dtype: int64

In [7]:
#remove rows with avg_transaction_value less than 0
data = data[data['points_in_wallet'] >= 0]
data.count()

age                             23041
gender                          23041
security_no                     23041
region_category                 23041
membership_category             23041
joining_date                    23041
joined_through_referral         23041
referral_id                     23041
preferred_offer_types           23041
medium_of_operation             23041
internet_option                 23041
last_visit_time                 23041
days_since_last_login           23041
avg_time_spent                  23041
avg_transaction_value           23041
avg_frequency_login_days        23041
points_in_wallet                23041
used_special_discount           23041
offer_application_preference    23041
past_complaint                  23041
complaint_status                23041
feedback                        23041
churn_risk_score                23041
dtype: int64

### Gender Col : F -> 0 ; M -> 1

In [8]:
from sklearn.preprocessing import OneHotEncoder

def apply_one_hot_encoding(df, column_name):

    df.dropna(subset=[column_name], inplace=True)
    # Create a new DataFrame with the specified column
    column_df = df[[column_name]]
    
    # Create an instance of OneHotEncoder
    encoder = OneHotEncoder()
    
    # Fit and transform the column using OneHotEncoder
    encoded_column = encoder.fit_transform(column_df)
    
    # Convert the encoded column to a dense array
    encoded_column_array = encoded_column.toarray()
    
    # Create a new DataFrame with the encoded column
    encoded_df = pd.DataFrame(encoded_column_array, columns=encoder.get_feature_names_out([column_name]))
    
    # Concatenate the original DataFrame and the encoded DataFrame
    encoded_df = pd.concat([df, encoded_df], axis=1)
    
    # Drop the original column from the encoded DataFrame
    encoded_df.drop(column_name, axis=1, inplace=True)
    
    return encoded_df

data = apply_one_hot_encoding(data, 'gender')
data = apply_one_hot_encoding(data, 'region_category')
data = apply_one_hot_encoding(data, 'joined_through_referral')
data = apply_one_hot_encoding(data, 'used_special_discount')
data = apply_one_hot_encoding(data, 'offer_application_preference')
data = apply_one_hot_encoding(data, 'past_complaint')
data = apply_one_hot_encoding(data, 'complaint_status')
data = apply_one_hot_encoding(data, 'feedback')
data = apply_one_hot_encoding(data, 'medium_of_operation')
data = apply_one_hot_encoding(data, 'internet_option')
data = apply_one_hot_encoding(data, 'membership_category')
data = apply_one_hot_encoding(data, 'preferred_offer_types')

,age,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,preferred_offer_types,medium_of_operation,internet_option,...,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score,gender_F,gender_M,gender_Unknown
0,18.0,XW0DQ7H,Village,Platinum Membership,17-08-2017,No,xxxxxxxx,Gift Vouchers/Coupons,?,Wi-Fi,...,781.75,Yes,Yes,No,Not Applicable,Products always in Stock,0.0,1.0,0.0,0.0
2,44.0,1F2TCL3,Town,No Membership,11-11-2016,Yes,CID12313,Gift Vouchers/Coupons,Desktop,Wi-Fi,...,500.69,No,Yes,Yes,Solved in Follow-up,Poor Website,1.0,0.0,1.0,0.0
3,37.0,VJGJ33N,City,No Membership,29-10-2016,Yes,CID3793,Gift Vouchers/Coupons,Desktop,Mobile_Data,...,567.66,No,Yes,Yes,Unsolved,Poor Website,1.0,1.0,0.0,0.0
4,31.0,SVZXCWB,City,No Membership,12-09-2017,No,xxxxxxxx,Credit/Debit Card Offers,Smartphone,Mobile_Data,...,663.06,No,Yes,Yes,Solved,Poor Website,1.0,0.0,1.0,0.0
5,13.0,PSG1LGF,City,Gold Membership,08-01-2016,No,xxxxxxxx,Gift Vouchers/Coupons,?,Wi-Fi,...,722.27,Yes,No,Yes,Unsolved,No reason specified,0.0,0.0,1.0,0.0

In [12]:
data.to_csv('clean.csv', index=False)